### PR TITLE
enhancement: randomize comment list

### PR DESCRIPTION
**Pull request by audrasjb**
Comments list should be displayed in random order 😊

### CODE REVIEW

**Comment by imath** [comment]
Hi @audrasjb 

I agree the default order for AntiConferences topics (Camp comments) should be randomized. Your JavaScript workaround is interesting, but as it applies to all order options, i'm afraid it can disturb some users when they chose to order by number of votes for instance.

I think the random order must be added to the available ones into `anticonferences_get_order_options()` (before "date_asc") so that it is used as the default one, then this new order should be handled in the second part of this function `anticonferences_parse_comment_query()`.

What's tricky with the random order is to carry on having consistent results for paginated ones (which is the case for topics). I've read this [post](https://hugh.blog/2013/08/22/wordpress-random-post-order-with-correct-pagination/) by @hlashbrooke which seems to do the trick for posts, i'm sure there is a way to do it for comments in our case (and preferably without using a session variable 😉).

**Comment by hlashbrooke** [comment]
Getting a ping from an unfamiliar repo only happens about once every few years for me, so thought I'd stop by to give some input :smile: 

The solution in that post is essentially a MySQL solution - the seed value for random ordering will work in any MySQL query, whether it's in WP or not. The session variable is necessary to make sure you keep the same seed value for all queries, so if you can find an alternative way of doing that, then I'd love to hear about it. Perhaps store the seed value as a transient with the user ID, then set the transient to expire after 1 hour? A little janky maybe, but it could work.

As far as I can tell from looking the WP core, however, there's no filter for the ORDER BY clause for comment queries, so you might have to do a later filter on the entire query if you want to modify that.

**Comment by imath** [comment]
Hi Hugh,

Thanks a lot for your explanations 👍

imath.
http://profiles.wordpress.org/imath/

**Comment by audrasjb** [comment]
Great job @imath @hlashbrooke !
Sorry for not being able to go further, I was too busy in recent days…
Glad to see that my workaround has led to a real improvement :)

Cheers,
Jb

**Pull request closed without merging**
